export default function Mainpage() {
  return (
    <div className="">
      Mainpage
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
      <div>gkgk</div>
    </div>
  );
}
